### ISSUE TITLE
Creeper acid?

### ISSUE THREAD

**Issue by psyon** [pWn3d1337/Techguns#20]
I can't find any information on how to make creeper acid.

**Comment by pWn3d1337** [comment]
Nei handlers for fluids will be fixed in the next version. If you click on Recipes in the chem lab you can view all recipes and there it's visible.

 The recipe is 1 Bucket Water (1000mB) + BioMass + Gunpowder in the chem lab. If you have mekanism its also possible with Water + 4 BioFuel + Gunpowder.
