### ISSUE TITLE
entity render crash

### ISSUE THREAD

**Issue by Cronosus** [pWn3d1337/Techguns#47]
hello
today my sp game crashes with this:
https://paste.ee/p/0bVOa

using latest forge, latest techguns and mods listed in log.

**Comment by pWn3d1337** [comment]
The problem is that the renderer of the handgun is creates a recursion, but this does not happen by vanilla or techguns alone. Some other mod inteferes here because in the call stack there are classes involved that I have nothing to do with. Specifically mdxlib and avp.

> at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at **com.arisux.mdxlib**.lib.client.render.Draw.drawEntity(Draw.java:749)
	at **org.avp.client.**gui.GuiTurret.func_146979_b(GuiTurret.java:145)

**Comment by Cronosus** [comment]
yes, i found its cause indise turret from AVP
but i cant use your mod on server, if this causes crash, and i like your mod and believe players on my server will be liking it too

**Comment by pWn3d1337** [comment]
Does it crash with all guns or just the handgun? Wait you want to use techguns for turrets from another mod? That won't work. Techguns can't shoot without special code.

Also this crash is caused by the other mod, so I'm not sure if I can fix this.

It seems like the GUI from some AVP turret crashes because it wants to render the Techguns turret entity which causes a recursive call on the itemRenderer of the Item the turret is holding. This is strange...

**Comment by Cronosus** [comment]
no, in avp is turret, inside this turret you can specifi targets. But when i roll inside between existing entities and reach this one, then it crashes. i dont know if this happens with another too, because i cant reach another.

**Comment by pWn3d1337** [comment]
I quickly looked through the code, this is strange. When I have the time I might test with the other mod, but hard to say why this happens, If it just renders a turret it should not even hold a gun that gets rendered.

**Comment by pWn3d1337** [comment]
I could find the problem. There was an old unsed turret entity still registered to the game. The next version (1.2 Alphatest 3) will contain the fix.

**Comment by Cronosus** [comment]
nice :)

**Comment by Cronosus** [comment]
fixed, thanks :)
